matrix:
  - name: Markdown
    aspell:
      lang: en_AU
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - pymdownx.superfences
      - pyspelling.filters.html:
          ignores:
            - code
            - pre
    sources:
      - '**/*.md'
