name: Lint
on: pull_request
permissions:
  contents: read
jobs:
  # Lint markdown.
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Install gem dependencies
        run: gem install mdl
      - name: Test (mdl)
        run: mdl *.md -s .mdl_style.rb
  # Check for grammar and spelling inconsistencies within the repository.
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.38.0
